<?php
/**
 * Implements hook_preprocess_page().
 */
function av_klaro_readspeaker_preprocess_page(array &$variables) {
  $variables['#attached']['library'][] = 'av_klaro_readspeaker/av_klaro_readspeaker';
}

/**
 * @file
 * Installations- und Deinstallationsfunktionen für das av_klaro Modul.
 */
/*
use Drupal\Core\Config\FileStorage;
use Drupal\Core\Config\StorageInterface;
*/
/**
 * Implements hook_install().
 */
 /*
function av_klaro_readspeaker_install() {
  $module_path = \Drupal::service('extension.list.module')->getPath('av_klaro_readspeaker');
  $config_path = $module_path . "/config/optional";

  if (!is_dir($config_path)) {
    \Drupal::logger('av_klaro_readspeaker')->error('Config-Ordner nicht gefunden: @path', ['@path' => $config_path]);
    return;
  }

  $storage = new FileStorage($config_path);
  $configs = [
    'klaro.klaro_app.av_readspeaker',
  ];

  foreach ($configs as $config_name) {
    $config_data = $storage->read($config_name);
    if ($config_data) {
      \Drupal::configFactory()->getEditable($config_name)
        ->setData($config_data)
        ->save();
      \Drupal::logger('av_klaro_readspeaker')->notice('Konfiguration @config wurde erfolgreich überschrieben.', ['@config' => $config_name]);
    } else {
      \Drupal::logger('av_klaro_readspeaker')->warning('Konfiguration @config nicht gefunden.', ['@config' => $config_name]);
    }
  }
}
*/
