<?php
   /**
    * hook_theme
    */
   function av_b_system_block_theme($existing, $type, $theme, $path) 
      {
         return [
         /*
               'paragraph__p_accordion' => [     
                     'base hook' => 'paragraph',
                  ],
               'paragraph__pi_accordion_item' => [     
                     'base hook' => 'paragraph',
                  ],
               'field__paragraph__field_p_a_accordion_item' => [     
                     'base hook' => 'field',
                  ],
                  */
               'field__field_b_sb_content' => [     
                     'base hook' => 'field',
                  ],
            ];
      } 