<?php

   /**
    * hook_theme
    */
   function av_p_file_theme($existing, $type, $theme, $path) 
      {
         return [
                   'paragraph__p_file' => [
                                                   'base hook' => 'paragraph',
                                              ],
                   'field__field_p_f_file' => [
                                                   'base hook' => 'field',
                                              ],
                   'field__file' => [
                                                   'base hook' => 'field',
                                              ],
               ];
      } 
      
   /**
    * Implements hook_preprocess_HOOK().
    */
   use Drupal\Core\GeneratedLink;
   function av_p_file_preprocess_file_link(&$variables) 
      {
         // Add target _blank attribute to all file links.
         $file = $variables['file'];
         #$url = file_create_url($file->uri->value);
         $url = \Drupal::service('file_url_generator')->generateAbsoluteString($file->uri->value);

         
         // Use the description as the link text if available.
         if (empty($variables['description'])) 
            {
               $link_text = $file->filename->value;
            }
         else 
            {
               $link_text = $variables['description']->__toString();
            } 
         
         // mime Text
         $mime_text = '';
         switch($file->filemime->value)
            {
               case 'application/pdf':
                  $mime_text = 'PDF';
               break;
            }
         $file_size = number_format(($file->filesize->value / 1024 / 1024),'2',',','.').' MB';
         $mime_text = (($mime_text)?$mime_text.' ':'');
         
         $link = '<a href="' . $url . '" type="' . $file->filemime->value . '" length="' . $file->filesize->value . '" title="' . \Drupal\Component\Utility\Html::escape($file->filename->value??'') . '" target="_blank">' . \Drupal\Component\Utility\Html::escape($link_text) . ' ('.$mime_text.$file_size.')</a>';
         #$variables['link']->setGeneratedLink($link);
         $variables['link'] = (new GeneratedLink())->setGeneratedLink($link);
      }