<?php
   /**
    * hook_theme
    */
   function av_p_single_location_map_theme($existing, $type, $theme, $path) 
      {
         return [
               'paragraph__p_single_location_map' => [     
                     'base hook' => 'paragraph',
                  ],
              # 'field__field_p_' => [     
              #       'base hook' => 'field',
              #    ],
            ];
      } 